<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 9:48
 */

namespace example\Form;

use Libs\Tools\Form;

class TestForm extends Form
{
    public function __construct($data)
    {
        parent::__construct($data);
        $this->extend();
    }

    public function rules()
    {
        return [
            'title' => 'required|string|min:2|max:5',
            'status' => 'required|integer',
            'test' => 'required|string|foo'
        ];
    }
    public function attributes()
    {
        return [
            'status'=>'状态',
            'test'=>'测试',
        ]; // TODO: Change the autogenerated stub
    }

    public function messages()
    {
        return [
            'foo' => ':attribute 不等于foo',
        ]; // TODO: Change the autogenerated stub
    }

    public function extend(){
        $this->_valid->extend('foo', function ($attribute, $value, $parameters) {
            return $value == 'foo';
        });
    }
}